### PR TITLE
check recipes at PR time

### PR DESCRIPTION
**Pull request by cdeepali**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/main/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/main/doc/)?
- [ ] Did you write any [tests](https://github.com/open-ce/open-ce/blob/main/tests/) to validate this change?  

## Description

Fixes https://github.com/open-ce/open-ce/issues/175.

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) requests changes, they must be addressed.

### CODE REVIEW

**Comment by bethune-bryant** [comment]
Could you make a test PR into a feedstock that updates the action to use this branch, to make sure that we didn't make any mistakes?

**Comment by cdeepali** [comment]
Yes, I have made test PR - https://github.com/open-ce/srsly-feedstock/pull/11

**Comment by bethune-bryant** [comment]
> 
> 
> Yes, I have made test PR - [open-ce/srsly-feedstock#11](https://github.com/open-ce/srsly-feedstock/pull/11)

Great, Looks good!

**Review by bethune-bryant — APPROVED** [review]

**Comment by cdeepali** [comment]
Thanks @bethune-bryant. Merging it.

**Pull request merged**
