### PR TITLE
change for default branch name

### PR DESCRIPTION
**Pull request by cdeepali**
Change for default branch name in the README.

### CODE REVIEW

**Comment by bnemanich** [comment]
Why is this being removed? It seems like we want to keep this line in. We should probably change line 5 of feedstock-pr.yml from master to main though.

**Comment by cdeepali** [comment]
Yes, that is already updated - https://github.com/open-ce/.github/blob/main/workflow-templates/feedstock-pr.yml#L5. So I thought this is not needed anymore. 

Do we still want to retain this?

**Comment by jayfurmanek** [comment]
yeah - we fixed that last week with the PRs @dncliss pushed.

**Comment by dncliss** [comment]
When I did the PR changes last week, I changed the wording in this section but I'd considered removing it entirely as @cdeepali does here.  I went ahead with the more minimal change just to make the review simpler for the mass-approval.
But really, I'm on board with this change.  Before the master/main switch, with some repos using one and a few using the other, a user might indeed have to edit this file to put the correct default branch name.  Now that all
repos have the same `main` default branch as reflected in this yaml file, there's no reason a human should need to edit the value, so it just becomes extraneous clutter information.

As per that opinion, I'm going to approve this -- but if there's not consensus on it then merging should probably wait.

**Review by dncliss — APPROVED** [review]
Approving; see my rationale in separate preceding comment.

**Comment by bnemanich** [comment]
OK, sounds good to me.

**Review by bnemanich — APPROVED** [review]

**Comment by cdeepali** [comment]
Thanks @dncliss, @bnemanich. merging this one.

**Pull request merged**
