### PR TITLE
Backported s390x fixes

### PR DESCRIPTION
**Pull request by ravigumm**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/main/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/main/doc/)?
- [ ] Did you write any tests to validate this change?

## Description
Backport two PRs https://github.com/apache/arrow/pull/11686 and https://github.com/apache/arrow/pull/11687
to arrow 5.0.0 and include in pyarrow-feedstock in open-ce

Fixes # (issue).

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) requests changes, they must be addressed.

### CODE REVIEW

**Comment by npanpaliya** [comment]
I think the patch should go into pyarrow-feedstock and pyarrow-feedstock recipe should be directly updated. 
`feedstock_patches` is usually used for remote (non open-ce) repos.

**Comment by cdeepali** [comment]
Yes, I am discussing this internally on slack.

**Comment by ravigumm** [comment]
ok

**Comment by ravigumm** [comment]
Created https://github.com/open-ce/pyarrow-feedstock/pull/31 and cancelling this open-ce PR

**Pull request closed without merging**
