### PR TITLE
Add cycle check.

### LINKED ISSUE #54: Find cycles in a BuildTree
Currently, it is possible to have cycles within a BuildTree. This can lead to infinite recursion when iterating over the tree. Add a function to detect cycles. Ideally, this would output the dependency cycle so that a user can fix the recipes.

### PR DESCRIPTION
**Pull request by bethune-bryant**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/master/CONTRIBUTING.md)?
- [x] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/master/doc/)?
- [x] Did you write any [tests](https://github.com/open-ce/open-ce/blob/master/tests/) to validate this change?  

## Description

Fixes #54

### CODE REVIEW

**Comment by bethune-bryant** [comment]
I did some runs and collected the runtime for various numbers of packages:
The maximum one was this run:
`./open-ce/build_env.py envs/opence-env.yaml --repository_folder ./repos/ --python_vers 3.6,3.7,3.8 --build_types cuda,cpu --mpi_types openmpi,system`
image

**Review by bnemanich — APPROVED** [review]
Looks good!

**Comment by bethune-bryant** [comment]
I made pytorch depend on horovod and tried to build the horovod env file, and got the following error:
```
[OPEN-CE-ERROR-14] Build dependencies should form a Directed Acyclic Graph.
The following dependency cycle was detected in the build tree:
pytorch-base -> horovod-feedstock -> pytorch-meta -> pytorch-base
pytorch-base -> horovod-feedstock -> pytorch-meta -> torchtext-feedstock -> pytorch-base
pytorch-base -> horovod-feedstock -> pytorch-meta -> torchvision-base -> pytorch-base
pytorch-meta -> pytorch-base -> horovod-feedstock -> pytorch-meta
pytorch-meta -> torchtext-feedstock -> pytorch-base -> horovod-feedstock -> pytorch-meta
pytorch-meta -> torchvision-base -> pytorch-base -> horovod-feedstock -> pytorch-meta
torchtext-feedstock -> pytorch-base -> horovod-feedstock -> pytorch-meta -> pytorch-base
torchtext-feedstock -> pytorch-base -> horovod-feedstock -> pytorch-meta -> torchtext-feedstock
torchtext-feedstock -> pytorch-base -> horovod-feedstock -> pytorch-meta -> torchvision-base -> pytorch-base
torchvision-base -> pytorch-base -> horovod-feedstock -> pytorch-meta -> pytorch-base
torchvision-base -> pytorch-base -> horovod-feedstock -> pytorch-meta -> torchtext-feedstock -> pytorch-base
torchvision-base -> pytorch-base -> horovod-feedstock -> pytorch-meta -> torchvision-base
torchvision-meta -> pytorch-base -> horovod-feedstock -> pytorch-meta -> pytorch-base
torchvision-meta -> pytorch-base -> horovod-feedstock -> pytorch-meta -> torchtext-feedstock -> pytorch-base
torchvision-meta -> pytorch-base -> horovod-feedstock -> pytorch-meta -> torchvision-base -> pytorch-base
torchvision-meta -> torchvision-base -> pytorch-base -> horovod-feedstock -> pytorch-meta -> pytorch-base
torchvision-meta -> torchvision-base -> pytorch-base -> horovod-feedstock -> pytorch-meta -> torchtext-feedstock -> pytorch-base
torchvision-meta -> torchvision-base -> pytorch-base -> horovod-feedstock -> pytorch-meta -> torchvision-base
horovod-feedstock -> pytorch-meta -> pytorch-base -> horovod-feedstock
horovod-feedstock -> pytorch-meta -> torchtext-feedstock -> pytorch-base -> horovod-feedstock
horovod-feedstock -> pytorch-meta -> torchvision-base -> pytorch-base -> horovod-feedstock
```

**Comment by bethune-bryant** [comment]
After seeing that output, I think alot of output could be generated if something went wrong, so I added a limit.
@bnemanich , what do you think?
```
[OPEN-CE-ERROR-14] Build dependencies should form a Directed Acyclic Graph.
The following dependency cycles were detected in the build tree:
pytorch-base -> horovod-feedstock -> pytorch-meta -> torchvision-base -> pytorch-base
pytorch-base -> horovod-feedstock -> pytorch-meta -> torchtext-feedstock -> pytorch-base
pytorch-base -> horovod-feedstock -> pytorch-meta -> pytorch-base
pytorch-meta -> torchvision-base -> pytorch-base -> horovod-feedstock -> pytorch-meta
pytorch-meta -> torchtext-feedstock -> pytorch-base -> horovod-feedstock -> pytorch-meta
pytorch-meta -> pytorch-base -> horovod-feedstock -> pytorch-meta
torchtext-feedstock -> pytorch-base -> horovod-feedstock -> pytorch-meta -> torchvision-base -> pytorch-base
torchtext-feedstock -> pytorch-base -> horovod-feedstock -> pytorch-meta -> torchtext-feedstock
torchtext-feedstock -> pytorch-base -> horovod-feedstock -> pytorch-meta -> pytorch-base
torchvision-base -> pytorch-base -> horovod-feedstock -> pytorch-meta -> torchvision-base
Cycles truncated after 10...
```

**Review by jayfurmanek — APPROVED** [review]

**Pull request merged**
